# Generated by Django 4.1.3 on 2022-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_level', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stage_map', models.CharField(max_length=3000)),
                ('stage_hint', models.CharField(max_length=3000)),
            ],
        ),
    ]
