# Generated by Django 4.1.3 on 2022-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stage_level', models.IntegerField()),
                ('rank_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=5)),
                ('stage_level', models.IntegerField()),
                ('record_code', models.CharField(max_length=3000)),
                ('record_complexity', models.IntegerField()),
                ('record_time', models.CharField(max_length=20)),
                ('record_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
            ],
        ),
    ]
