# Generated by Django 4.1.3 on 2022-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_record_record_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_score',
            field=models.IntegerField(null=True),
        ),
    ]
